### ISSUE TITLE
Enhance RDF performance

### ISSUE THREAD

**Issue by daglu** [digicademy/svsal#19]
Currently, RDF extraction for large works (>50,000 lines) takes an inacceptable amount of time (e.g. W0002: at least 4 days), and the amount of time clearly seems to grow exponentially with the size of documents. Thus, especially with regards to very large works (>100,000 lines), the extraction should scale much better.

**Comment by daglu** [comment]
Just an idea: if the extraction loads TEI documents via http at several points, probably it would be faster to load them rather by means of direct database access?

**Comment by awagner-mainz** [comment]
I suggest to close this as, AFAICT, rdf generation is much quicker now. Still takes some time, but to me it no longer qualifies as a bug. And in terms of enhancement, we should re-open it when we have a concrete idea of how to further improve it.
