### ISSUE TITLE
TEI/XML Corpus Download

### ISSUE THREAD

**Issue by awagner-mainz** [digicademy/svsal#2]
- [x]  Fix creation of corpus zip file (Currently, I get a zipfile with 0-byte W...xml files)
- [x] Offer as a download from "works" page

**Comment by awagner-mainz** [comment]
Done. However, we should define a policy and a filter for which works must not be included in the corpus due to their preliminary status.

**Comment by daglu** [comment]
In the current deployment scheme, works are only deployed as full TEI once the text is completely edited and corrected, such that datasets for works with preliminary status only contain metadata. Hence, marking this as closed.
