### ISSUE TITLE
Add link to facsimiles/mirador in workDetails

### ISSUE THREAD

**Issue by awagner-mainz** [digicademy/svsal#24]
This is especially applicable in cases where we don't have the fulltext yet.

We could, in these cases, use the thumbnail link to link to mirador instead of the (non-existent) reading view, or we could add a new link. I would prefer the latter in order to be more consistent and not have the same button (the tumbnail) behave differently according to different circumstances.

**Comment by daglu** [comment]
Closing this issue, since it is already solved in develop branch.
