### ISSUE TITLE
Link to Opac (on workDetails.html) should respect language setting

### ISSUE THREAD

**Issue by awagner-mainz** [digicademy/svsal#25]
The MPIeR's OPAC accepts a url parameter "&Language=en", otherwise it defaults to German. We could add this parameter to the respective OPAC-links in the English and Spanish version of our workDetails page.

**Comment by daglu** [comment]
This is an even wider issue which extends this app: we need to state multiple language links (if available) in teiHeader//msDesc, and (in the app) implement a language-negotiation mechanism for dealing with links for non-available languages.
