### ISSUE TITLE
Offer citation recommendations for works

### ISSUE THREAD

**Issue by dvglc** [digicademy/svsal#30]
- [x] (1) discuss the format of citations in the larger scholars' team
- [x] (2) display citation recommendations for work in reading view
- [x] (3) display citation recommendations per passage in reading view (does this make (2) obsolete?)
- [x] (4) display recommendations in catalogue records (per work/volume)

**Comment by daglu** [comment]
Definitely include citation references for passages (as discussed). For doing so, we need to build a list/map of div/@type values that are to be included in references:  #34
