### ISSUE TITLE
Differentiate work editor groups

### ISSUE THREAD

**Issue by dvglc** [digicademy/svsal#31]
Rather a suggestion than a clearly determined issue, depending on whether the team decides that this actually makes sense and is achievable without complications. If so, the question arises where and how to display different categories of editors (such as main editors, technical editors, further participants...) in catalogue records, and perhaps also in other places.

**Comment by daglu** [comment]
Conceptually resolved: we differentiate between two major classes of editors (scholarly and technical) in catalogue records of works, while also linking from team members' profiles to the works they have contributed to. Profile pages shall also hold more detailed information about the types of activity of a member in the project.

**Comment by daglu** [comment]
In catalogue records, editors should be sorted within their "class" according to amount/importance of contribution (and not alphabetically, as was the case thus far).

**Comment by dvglc** [comment]
Postponing this to 1.6, since it isn't really urgent atm (but should be done before 2.0).

**Comment by awagner-mainz** [comment]
is this solved?

**Comment by dvglc** [comment]
Basically, yes. There is still the missing link between team members' profile pages and the type of editing work (and the works) they have participated in, but I have opened a specific issue for that (#83).
