### ISSUE TITLE
Clear separation of TEI data, derivative data, and app

### ISSUE THREAD

**Issue by dvglc** [digicademy/svsal#44]
ATM some derivative data (HTML, TXT, Sphinx snippets) are housed in the app, while others (RDF, IIIF) are packaged together with the TEI data, such that 
a) HTML, TXT and snippets need to be re-rendered every time a new version of the app gets deployed; this is extremely time-consuming and makes CD downright impossible
b) RDF and IIIF are tightly coupled to the TEI data, where it is not clear whether and when they need to be rendered in case a new version of a respective TEI dataset is deployed
c) this does not allow for clean versioning of TEI and derivative data

I propose that we clearly distinguish and separate three different data packages:
- [x] 1.) TEI data
- [x] 2.) derivative data: HTML, TXT, snippets, RDF, IIIF (+ EPUB etc. in the future) -> (some of) these could be triggered to render every time a respective dataset from 1.) is deployed
- [x] 3.) the actual app data/logic

**Comment by daglu** [comment]
I propose that we put sal:index data into 2.) as well, since they represent a derivative (if utility) data format

**Comment by daglu** [comment]
See also #27
