### ISSUE TITLE
[oxygen plugin] character 'long s' highlighted in red

### ISSUE THREAD

**Issue by dvglc** [digicademy/svsal#50]
In the author view ("Standard" style), the 'long s' character ``<g ref="#char017f">ſ</g>`` appears in red font size, like all other characters marked as ``<tei:g>``. This seems irritating to editors due to the character's high frequency - perhaps we can omit colorful highlighting with this special character only?

**Comment by dvglc** [comment]
I think this can be closed now.

**Comment by CindyRicoCarmona** [comment]
The 'long s' character <g ref="#char017f">ſ</g> looks very similar to the "f" in the author view. This makes difficult for the editors the recognition of corrections. Could it be possible to give a different color to 'the long s' to improve readability?
