### ISSUE TITLE
Revise format of "passage trails"

### ISSUE THREAD

**Issue by dvglc** [digicademy/svsal#61]
- [x] URI (+ access date) *after* trail of specific passage (i.e., at the very end of the citation)?

**Comment by awagner-mainz** [comment]
I suppose we can refrain from defining a publication place in the end. With regards to the last point, the reason I brought this up was that it looked funny if on both levels we only have text-only elements (in one particular case the name was even the same, although that might have been an accident) - maybe we should look some more for corner cases before deciding.

**Comment by dvglc** [comment]
@awagner-mainz 
Something like 'praef. praef.' is certainly an accident, I will look into this again. 

We can add commas between text-only elements, but then we might get inconsistent in other corner cases: e.g., 'praef., sect. 1 not. "a" ' where there is a comma between the first two, but not the last two elements. 

Perhaps, instead of trying to adapt to every possible corner case, we should keep it simple and consistent (and always do or do not add a comma)?

**Comment by dvglc** [comment]
'praef. praef.' is due to the underlying TEI markup in W0015 (div[@type eq 'preface'] within div[@type eq 'preface']). I think this shows very nicely the limitations of automatically generated citations: they can only be as good as the underlying markup...

**Comment by dvglc** [comment]
Decided against 'comma between each hierarchical level', at least for the moment.

**Comment by dvglc** [comment]
@awagner-mainz 
Pulling passage trails before the URI, would they occur 
1.) immediately after the title:
``Castillo, Tratado de Cuentas (2018 [1522]), pars 1 paragr. "QVanto a la pri…", in: Die Schule von Salamanca. Eine Digitale Quellensammlung, hg. von Thomas Duve & Matthias Lutz-Bachmann <https://id.c106-211.cloud.gwdg.de/texts/W0004:1.1?format=html> (Aufgerufen am 20. August 2019)``
(this is how I understand it)

or 

2.) immediately before the URI:
``Castillo, Tratado de Cuentas (2018 [1522]), in: Die Schule von Salamanca. Eine Digitale Quellensammlung, hg. von Thomas Duve & Matthias Lutz-Bachmann, pars 1 paragr. "QVanto a la pri…"<https://id.c106-211.cloud.gwdg.de/texts/W0004:1.1?format=html> (Aufgerufen am 20. August 2019)``
?
