### ISSUE TITLE
Illegal whitespace created during TEI export

### ISSUE THREAD

**Issue by dvglc** [digicademy/svsal#74]
Observed in W0034:

`

                    <tei:g ref="#char017f">ſ</tei:g>onas excelentes <tei:choice xml:id="W0034-00-0003-ce-041a">
                        <tei:abbr>
                            <tei:g ref="#char204a">⁊</tei:g>
                        </tei:abbr>
                        <tei:expan resp="#CB" cert="high">y</tei:expan>
                    </tei:choice> yo lo he comen<tei:g ref="#charc0327">ç</tei:g>ado a collegir delo
`

Apparently eXist tries to pretty-print something here, but doing so in mixed-content elements such as tei:abbr is clearly illegal since it adds text nodes where there were none before. An XML-based solution might be `@xml:space=preserve`.

**Comment by awagner-mainz** [comment]
More often than not, I've seen this in oXygen rather than in eXist-db. Maybe worth checking out that all formatting and pretty-printing there is disabled, too. I've tried to provide for that as far as I could via the svsal-framework, but you never know what the configuration is in individual installations and whether it's overridden by a local option.

**Comment by dvglc** [comment]
oXygen might also be problematic with regards to pretty-printing, but this one occurred while requesting TEI from our application: http://id.salamanca.school/texts/W0034?format=tei. The data for W0034 in the svsal-tei package/app is okay, so that something must happen during exporting the data. (An other indicator that eXist is doing additional stuff is that some elements suddenly have `tei:` prefixes after the export, which isn't really an issue, but somewhat strange nonetheless...)

**Comment by dvglc** [comment]
https://github.com/digicademy/svsal/commit/27bbed7cdc4823c2452388517901b0f4e4e92238 is not an elegant solution since it globally suppresses indentation in the document, but serialization parameters in util:expand() have proven not to work as described in the [eXist docs](http://exist-db.org/exist/apps/fundocs/index.html) (at least not with our way of using util:declare-option() at the same time).
