### ISSUE TITLE
Export TEI also per passage

### ISSUE THREAD

**Issue by awagner-mainz** [digicademy/svsal#9]
For a given section:

- [x] resolve XIncludes,
- [x] add opening and closing tags that are missing in the range actually requested,
- [x] reconstruct all necessary parent elements and wrap them around the section,
- [x] add a teiHeader

Then:

- [x] In the "hand" menu, add options to download plaintext and TEI for this passage only.

**Comment by dvglc** [comment]
Section ranges are not yet available, but I suggest we implement that together with #26 .
