### ISSUE TITLE
Marginalnoten im Fließtext 

### ISSUE THREAD

**Issue by phoenix-mossimo** [digicademy/svsal#96]
>AW: Die Marginalnoten tauchen auch im Fließtext selbst auf?

**Comment by phoenix-mossimo** [comment]
_Die Lösung von MAH:_ 
>Meinerseits habe ich die Lösung für die Marginalnoten im Text gefunden.
>grob gesagt, brauchen wir 2 Templates:
> - 1 generelle Template für tei:note, wo die Note durch einen leeren <xsl:text> ersetzt wird.
> - 1 Template tei:note mit einem "mode", wo wir die Regel für die zweite Spalte nennen. 

Laut MAH's Vorschlag noch ein Template eingefügt: 

`<xsl:template match="//tei:note"/>`

Für Marginal Notes ist weiterhin `<xsl:template match="//tei:note" mode="only">` verantwortlich, die die Notes am rechten Rand ausgibt.

**Comment by awagner-mainz** [comment]
Prima. Vielleicht kann man wie bei html/css-floats eine Art "clear" am Abschnittsende einfügen, so dass Leerraum, um die Marginalnoten zu Ende laufen zu lassen, nicht am Dokument-Ende kumuliert, sondern nach jedem Abschnitt... Ist auch nur eine Zwischen-Verbesserung, aber vielleicht eine Idee. (Und ich habe _keine_ Ahnung, ob das in XSL/FO geht!) Oder vielleicht habt ihr es auch schon so eingerichtet, das konnte ich auf die Schnelle nicht erkennen.

**Comment by MariaHu** [comment]
Ich habe einen Leerraum gelassen, weil ich bei Erarbeitung der note @anchored="false" die Stelle sofort sehen, cf. #issue97
